version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2022-09-25T15-44-53Z
    container_name: morty.minio
    restart: "unless-stopped"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: curl -f "http://localhost:9000/minio/health/live
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-data: