name: Checks
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - id: go-version
        run: echo "version=$(cat ./.go-version)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.version }}
          cache: true
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
