on:
  release:
    types: [created, published]

jobs:
  release-binaries:
    name: Release binaries
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
    - uses: actions/checkout@v3
    - id: go-version
      run: echo "version=$(cat ./.go-version)" >> $GITHUB_OUTPUT
    - uses: wangyoucao577/go-release-action@v1
      with:
        pre_command: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
        github_token: ${{ secrets.GITHUB_TOKEN }}
        extra_files: LICENSE README.md
        project_path: "."
        binary_name: "morty"
        asset_name: morty-${{ matrix.goos }}-${{ matrix.goarch }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: ${{ steps.go-version.outputs.version }}
